### ISSUE TITLE
Update all mentioned of Multi-Tier-Cloud with PhysarumSM

### ISSUE THREAD

**Issue by hivanco** [PhysarumSM/PhysarumSM#10]
Including go module names, license comments, hyperlinks

**Comment by hivanco** [comment]
Planning to give all modules an updated tag while I'm at it.
@t-lin is there a reason service-manager requires a specific commit from common, but an updated tag for common was not created?

**Comment by t-lin** [comment]
@hivanco No particular reason. I wasn't sure if I was going to be making any more commits in `common` anytime soon, and also to avoid creating too many unnecessary tags. I was hoping to bundle a few more commits/features together before tagging a new version. You can go ahead and create a new tag if you want.
