### ISSUE TITLE
Brainstorm new name for this entire project

### ISSUE THREAD

**Issue by t-lin** [PhysarumSM/PhysarumSM#7]

**Comment by hivanco** [comment]
Interconnected Microservice Hosting Architecture Technology (IMHAT)
High Tolerant Interconnected Microservice Architecture (HTIMA)

**Comment by t-lin** [comment]
Little Python program to permutate the acronym...

```
#!/usr/bin/python
def permutate(soFar, remaining):
    if len(remaining) == 0:
        print soFar
        return

    for nextLet in remaining:
        newSoFar = soFar + str(nextLet)

        remainCopy = list(remaining)
        remainCopy.pop(remainCopy.index(nextLet))
        permutate(newSoFar, remainCopy)

permutate("", list("IMHAT"))
```

**Comment by mwyzhao** [comment]
Cloud Themed:
Atmosphere
Atmos
Nimbus
Cumulus
Stratus
Rain

Water Themed:
Gutter
Drain
Aqueduct (the name I named the protocol I made in the summer)

Random:
RAC (random access containers)

**Comment by t-lin** [comment]
For the acronym idea: AH could be "Auto-Healing" and M could be "Mesh", since this is a type of service mesh.

**Comment by hivanco** [comment]
Follow up to the tardigrades (immortal water bears) theme, seems like no one knows how they communicate. Their known means of perception are eyes and "sensory bristles".

**Comment by t-lin** [comment]
Some other suggestions:
  - **Tun**: When tardigrades are deprived of water or nutrients, they curl up into a state called "tun", when they become virtually immortal. Also kinda fits since P2P essentially tunnels traffic.
  - **Agar**: Agar is the culture medium used in many petri dishes for growing micro-organisms, providing the necessary water and nutrients for them to grow.
  - **Slime**: Not a very attractive name, but I was basically thinking of slime mold (they're pretty neat, see: https://www.youtube.com/watch?v=40f7_93NIgA). Basically, they're "intelligent" self-organizing mold. If you check out the video about how they move and communicate, it's very P2P-like.

**Comment by hivanco** [comment]
DAHMM (pronounced like when someone goes "dayum!") - Decentralized Auto Healing Microservice Mesh

**Comment by t-lin** [comment]
We should probably put these to a ranked vote...

**Comment by hivanco** [comment]
There is both an org and repo named slime on github already. Agar, tun, and tardigrade are all users on github. So uses of these names might need some modification.

A format we could use is a name followed by an abbreviation, eg. DB (MongoDB, DynamoDB), CI (CircleCI, Travis CI) and the many startups ending in ".io". Maybe something like, TardigradeSM (service mesh).

**Comment by mwyzhao** [comment]
I like the sound of SlimeSM, it flows off the tongue. I think it would work  for a product targeted towards developers, not sure if it's appropriate for a paper.

**Comment by t-lin** [comment]
> not sure if it's appropriate for a paper.

That's kinda why I like it. 😅

**Comment by mwyzhao** [comment]
To make it even more absurd we can make it SlimeSH and the end looks like Sli(meSH). SH can stand for self-healing or something like that, though I would say overall it doesn't sound as nice.

**Comment by mwyzhao** [comment]
![Untitled1_20200720214638](https://user-images.githubusercontent.com/21133720/88003403-cc6f2380-cad2-11ea-8c47-a194df451f7a.png)
We could even have a logo that looks something like this, we can tweak it to make it look less like a garbage bag but you get the idea.

**Comment by hivanco** [comment]
Some of these are terrible but I feel like I should share these last minute ideas anyways:
- Some organisms are considered "biologically immortal"; they do not appear to die from old age, their cells continually divide and regenerate
  - Hydra, a genus of small, fresh-water organisms. Could also refer to the mythical beast.
  - Turritopsis dohrnii, the immortal jellyfish. Would need to turn this into a simpler name.
- I read someone relate the spreading of disease to the propagation of information in a peer-to-peer network, and how hosts have a state of health, but debatable whether it's a good idea during these times
- Dragon - Decentralized Regenerating Auto Growing Open Network - thought dragon would sound cool, but was hoping to think of something better for O
- Adapt - Auto Discovering Across Peer Transmission. Or even without using an acronym, the definition of adapt is to become adjusted to new conditions. Sort of covers the ability to monitor conditions and allocate new services accordingly.
- Dash - Decentralized Auto Scaling Healing. Hopefully our system is also fast, hence "dash".
- Shade - Self Healing Auto Discovering Ecosystem
- Dad SM - Decentralized Auto Discovering Service Mesh
- iCare - Inter Connecting Auto Regenerating Ecosystem, or just CARE without the "Inter". Related: Race - rearrange the words. Scare - the S stands for scaling.

I had this list of adjectives/verbs {decentralized, auto, self, scaling, growing, connecting, discovering, healing, regenerating, monitoring} and nouns {microservice, service, mesh, network, peer} in case that sparks any ideas.

**Comment by hivanco** [comment]
> We could even have a logo that looks something like this, we can tweak it to make it look less like a garbage bag but you get the idea.

Lol is that a droplet of slime?

**Comment by t-lin** [comment]
> Some of these are terrible but I feel like I should share these last minute ideas anyways:

We should do a vote on Thursday. For now, in the paper I've avoided naming it directly, I just keep saying "the system" or "our system".

>   * Hydra, a genus of small, fresh-water organisms. Could also refer to the mythical beast.

Hydra does sound cool. Cut off one head, another grows.

>   * Turritopsis dohrnii, the immortal jellyfish. Would need to turn this into a simpler name.

Seems pretty cool. I like things that are a bit vague and adds some mystery.

> Lol is that a droplet of slime?

The "slime" I had in mind looks something like this: https://www.wired.com/2010/01/slime-mold-grows-network-just-like-tokyo-rail-system/

**Comment by t-lin** [comment]
Accepted in Jul. 23rd meeting: PhysarumSM 

Heavily rejected: DadSM
