### ISSUE TITLE
Setup continuous integration?

### ISSUE THREAD

**Issue by t-lin** [PhysarumSM/PhysarumSM#9]
Reference: https://github.com/ligurio/awesome-ci

CodeShip: free for open source no numbers, have to sign up to see: https://codeship.com/pricing
Github Actions: 2000 minutes free for open source: https://github.com/features/actions
RazorOps: 1 x cpu for free, has (separate?) free open source plan but no numbers, has to do with k8s: https://razorops.com/pricing
Semaphore: 4 x linux + 1 x macOS free for open source: https://semaphoreci.com/pricing
Travis CI: 5 concurrent jobs free for open source: https://travis-ci.com/plans

Also see: https://medium.com/@_oleksii_/set-up-automated-builds-using-github-and-docker-hub-12c3e0f18eba

**Comment by mwyzhao** [comment]
Probably needs to be a test suite before continuous integration

**Comment by t-lin** [comment]
The `docker-driver` repo and the `common/util` package has some test cases already. We can probably try and set up some basic case where those tests get automatically executed?

I did do a simple test using Github workflows a couple weeks ago, which kicks off a build task for each commit in a specific branch (see: https://github.com/PhysarumSM/monitoring/tree/workflowtest). Seems to work well, though we're limited in the number of free minutes/actions we get per month.

**Comment by mwyzhao** [comment]
@PhysarumSM/capstone-bros not sure who's interested but I updated the main comment with some choices for CI maybe we could make a decision and I could set it up.

My choice personally would probably be Semaphore or TravisCI.

**Comment by t-lin** [comment]
Since I don't have much experience, I'm personally open to any one of them. I'd prefer the easiest one to learn, use, and debug (sometimes this means sacrificing features/capabilities, though it's questionable if we need something complex right now).

What're the factors in your preferences? The number of free jobs/builds? Or are there features and other UX factors you see that you particularly like?

**Comment by mwyzhao** [comment]
I haven't looked too deeply into it but I just picked based on number of machines they offered. I don't have any experience with CI either so there's basically no other reason.

I think what you're saying makes sense, and in that case Github Actions is also a good option as it should be more than enough for us and from the sounds of it its already working.

**Comment by mwyzhao** [comment]
Since no one had anything else to say, I setup Github Actions to run go build and go test on `service-manager` and `common` repos for now, I'll setup Github Actions for the other repos as well over time. I realized that Github Actions runs on a per repo basis, so each of our repos actually gets 20 concurrent jobs and 2000 minutes in a month, so more than enough for what we need.

Next steps is definitely to add in more tests

**Comment by t-lin** [comment]
Thanks Michael!
